---
version: '3.3'
services:
  funfact:
    image: mishiklakus/kursova:latest
    build:
      context:Telegrambot/.
      dockerfile: Dockerfile
    container_name: funfact
    environment:
      MY_TG_BOT_TOKEN: ${MY_TG_BOT_TOKEN}
    networks:
      - back-tier

networks:
  back-tier: